### ISSUE TITLE
redefinition of htobeXX in some linux versions

### ISSUE THREAD

**Issue by d70-t** [blizzard4591/cmake-portable-endian#1]
In my current linux endian.h, some htobeXX functions are already defined and yield a redefinition warning. I did a quick fix under d8e427726808a4c5726c17b2915f0e61f8bb7a86, but it would be better to find a clean solution. What do you recommend?

**Comment by blizzard4591** [comment]
Could you please post the part of your endian.h which defines these macros and tell me which version/distro you are using?

**Comment by d70-t** [comment]
I am using Ubuntu 16.04 LTS and gcc 5.3.1 (standard installation).

This is the snippet from endian.h:

``` c
#if defined __USE_MISC && !defined __ASSEMBLER__
/* Conversion interfaces.  */
# include <bits/byteswap.h>

# if __BYTE_ORDER == __LITTLE_ENDIAN
#  define htobe16(x) __bswap_16 (x)
#  define htole16(x) (x)
#  define be16toh(x) __bswap_16 (x)
#  define le16toh(x) (x)

#  define htobe32(x) __bswap_32 (x)
#  define htole32(x) (x)
#  define be32toh(x) __bswap_32 (x)
#  define le32toh(x) (x)

#  define htobe64(x) __bswap_64 (x)
#  define htole64(x) (x)
#  define be64toh(x) __bswap_64 (x)
#  define le64toh(x) (x)

# else
#  define htobe16(x) (x)
#  define htole16(x) __bswap_16 (x)
#  define be16toh(x) (x)
#  define le16toh(x) __bswap_16 (x)

#  define htobe32(x) (x)
#  define htole32(x) __bswap_32 (x)
#  define be32toh(x) (x)
#  define le32toh(x) __bswap_32 (x)

#  define htobe64(x) (x)
#  define htole64(x) __bswap_64 (x)
#  define be64toh(x) (x)
#  define le64toh(x) __bswap_64 (x)
# endif
#endif
```

**Comment by blizzard4591** [comment]
Found the problem: I declared -std=c99 for GCC, but this disables the macro declarations in endian.h

**Comment by blizzard4591** [comment]
Fixed in cba1b5232e509aae1f0b6916f11fed4c995a11df.

**Comment by d70-t** [comment]
thanks a lot, works perfectly now

**Comment by blizzard4591** [comment]
Thank you for using my work and reporting bugs, always happy to help :)
