### ISSUE TITLE
use CMake caching more aggressively

### ISSUE THREAD

**Issue by fogti** [blizzard4591/cmake-portable-endian#3]
I rerun cmake multiple times per hour on some projects and the cmake-portable-endian subproject takes a very long time because it reruns a part every time (the compiler/function detection) that currently isn't cached and wastes time in a cmake-make-make install-test cycle.

problematic part output:
> -- Trying to use system implementation of endian conversion methods if available.
> -- Compiler has %zu support.
> -- Compiler: GNU CC
> -- Detected Non-OpenBSD Style Unix leNNtoh functions.
> -- Did not detect OpenBSD Style Unix letohNN functions.
> -- Detected GCC Style __builtin_bswap functions.
> -- Detected 16bit hton/ntoh functions.
> -- Detected 32bit htonl/ntohl functions.
> -- Collected endianness information...
> -- Success! The generated portable endian config file seems to work!
> -- Programs need to be linked with

**Comment by blizzard4591** [comment]
I have never used this library that much, so I can see that these features might be lacking ;)
Do you use this library "in production"? If you are interested, I can give you write access to the repository - a maintainer is always welcome!

**Comment by fogti** [comment]
I don't really use this library "in production", simply because I have only 1 project where I use it (zsdbp5) and this project is still between alpha and beta stage.
